name: Export GameCI license
on:
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt-get -y install gnupg
          gpg --import-ownertrust .github/workflows/gameci-license-recipient.gpg
          echo "foo" | gpg --encrypt -a --recipient bd_@nadena.dev
