name: Export GameCI license
on:
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt-get -y install gnupg
          gpg --import .github/workflows/gameci-license-recipient.gpg
          echo "$UNITY_LICENSE" | gpg --encrypt -a --trust-model always --recipient export-key@nadena.dev
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
